---
title: Reflection - The Boston Marathon
author: Leonardo D. Palomera
date: '2019-04-20'
categories:
  - Boston Marathon
  - R
  - Running
tags:
  - Academic
  - R Markdown
output: html_document
subtitle: Leonardo's Boston Marathon Post Race Reflection
---


As of today April 2019, I have finished six marathons. No matter how the preceding 26.2 miles have played out, I’m always thankful that my body has withstood the distance and my mind has managed its aversion to suffering. It also feels good to stop.
Unlike each of the six marathons I’d run before, my feeling upon crossing the finish line in this year’s Boston Marathon was joy. 

Running a marathon is a little bit like coaching a group of synchronized swimmers: there are endless variables to manipulate and coordinate, and when they all come together, it’s a beautiful thing. But one small blip can throw the whole performance off. Some elements of marathoning—like pacing plans, racing flats, and fueling strategies—are under the control of the racer and easily fine-tuned in advance.

Others—like weather conditions, side stitches, and an erratic pace fuel by adrenaline—are maddeningly out of our control. All we can do is prepare our best, hope for minimal surprises on race day, and manage those that arise as well as we can.

Boston is such a memorable course, but I can’t say I remember much of it. Of course, the Wellesley Scream Tunnel, tuning left on Boylston St, creasing Heartbreak Hill are instances in which I remember contemplating but nothing special. My most memorable moments are as followed.

1. During the first nutrition stations, I fumbled a  Cliff “Shot” Energy. Looking back, mentally, that moment could have crushed my concentration and focus going forward. To my surprise, seconds later I notice a “Shot” dangling in front of me. The runner next must have heard my heavy sigh as I fell back in line with the pack. After some none verbal exchanges of expressions, I accepted his gift and we back to racing. Fortunately, we finished seconds apart and I was able to properly thank him, a hug and un-coherent few words.

2. I felt strong through the hillier sections Boston has to offer. And with all due respect to “Heartbreak Hill,” it wasn’t as tough as people said. I do however remember Wayne Leonard, a project manager whom I’ve worked with since moving to Denver, running alongside me. His attempt to take a picture while sprinting uphill was comical to say the least. I think for the first time during the race, I smiled and knew the worst sections were behind me.

The same reasons that make the marathon so hard to nail, and so crushing when we don’t, make a good marathon immensely satisfying. It’s not often that all of the main variables align exactly when they need to: a healthy, fit, and rested body; a crisp, still day; similarly matched competitors to work and battle with; a well-executed race plan; and minimal road bumps over a 26.2-mile. I was happy to cross the finish line at 2:45:33, a personal best of nearly 10 minutes. 

A special thanks to [Luis Guevara](https://www.instagram.com/luisreyguevara/) and [Daniel Herrera](https://www.instagram.com/corredaniel/) for making a memorable course and scratching one of six off the bucket list.



